### ISSUE TITLE
Local SSL Support

### ISSUE THREAD

**Issue by dasrecht** [pygmystack/pygmy-legacy#11]
We saw several use cases where local SSL support would be needed, as a lot of sites are built and ran ssl-only.

Part of pygmy already supports ssl, due to the recent changes on how we build the containers this is broken.

**Comment by derpaschi** [comment]
This is definitively a use case for us. Nearly all of our production sites are ssl only.

**Comment by ocean90** [comment]
💯 HTTPS is also required for quite a few new browser features which are only available for HTTPS.

**Comment by AlexSkrypnyk** [comment]
@Schnitzel @twardnw Is there any chance this can be addressed any time soon?

**Comment by ocean90** [comment]
Note that Google Chrome is now labeling any website not using HTTPS as "not secure". It's only a local site, yet quite annoying.

**Comment by ocean90** [comment]
I have been told that the current issue is with pygmy that it needs to support legacy and lagoon containers since not everyone has already switched to the lagoon containers. But those who haven't switched would probably also not update their pygmy version. So, if [semantic versioning](https://semver.org/) is followed, 1.0.0+ could only support lagoon containers and if you require support for legacy containers you'd install 0.9.x.
 
```
gem install pygmy -v '~> 0.9' # legacy
gem install pygmy -v '~> 1.0' # lagoon
```

**Comment by tobybellwood** [comment]
handling in https://github.com/pygmystack/pygmy/issues/381
