### ISSUE TITLE
Please make ports configurable

### ISSUE THREAD

**Issue by rhubarbselleven** [pygmystack/pygmy-legacy#46]
I may have existing services already running and may not want to shut them down in order to develop.

Please make this here: https://github.com/amazeeio/pygmy/blob/master/lib/pygmy/haproxy.rb#L17 configurable

**Comment by rhubarbselleven** [comment]
Also, as a developer I cannot rely on being able to bind privileged ports due to not having privilege escalation

**Comment by fubarhouse** [comment]
FYI:

Ports `80` and `443` are the only ports which will work because of the `haproxy` configuration.

* https://github.com/amazeeio/docker-haproxy/blob/master/haproxy.tmpl#L29
* https://github.com/amazeeio/docker-haproxy/blob/master/haproxy.tmpl#L51

An example of exposing a different port can be found in the link below, but `pygmy` would still need to be wired up accordingly.
* https://github.com/fubarhouse/docker-haproxy/commit/70317d602268a3dfae1f9df832b7162a946a0b1e

**Comment by rhubarbselleven** [comment]
That could delegate to a variable as well. Further down you can see where
you’re pulling in the Amazee env variables.

Port 443 is still a privileged port and in a development environment we may
not be able to bind these ports either for preference or because of not
having access rights to do so.

**Comment by fubarhouse** [comment]
Check out the PR - if you use that version you can run `pygmy up` and it will only bind to port 80.
`pygmy up --port 443` will run the container on port 443 for HTTPS.

You may need to remove the containers if they've already been created prior to use though - `pygmy stop -d`

**Comment by dpacassi** [comment]
Subscribing as I'd like to see configurable ports too if that's somehow possible.

**Comment by tobybellwood** [comment]
https://github.com/pygmystack/pygmy supports this
